### PR TITLE
New docs

### PR DESCRIPTION
**Pull request by Brentlok**
## Summary

New docs for Unistyles 2.0 🦄🦄🦄

### CODE REVIEW

**Review by jpudysz — APPROVED** [review]

**Comment by dealvz** [comment]
@jpudysz are you hosting old docs anywhere? some of us will not use 2.0 yet and having old docs available is still very useful

**Comment by jpudysz** [comment]
Hello @dealvz !
As of now, we don't. It's because Astro lacks a versioning system. However, I have a copy of v1. I will host it somewhere else in 1-2 days. Sorry for the inconvenience.

**Comment by jpudysz** [comment]
@dealvz copy is now hosted here: https://reactnativeunistyles.vercel.app/v1/docs/start/setup 🙂

**Comment by dealvz** [comment]
> @dealvz copy is now hosted here: https://reactnativeunistyles.vercel.app/v1/docs/start/setup 🙂

amazing, thanks @jpudysz!

**Pull request merged**
