### PR TITLE
feat: implement content size category

### PR DESCRIPTION
**Pull request by jpudysz**
## Summary

Implements https://developer.apple.com/documentation/uikit/uicontentsizecategory?language=objc based on https://developer.apple.com/design/human-interface-guidelines/typography#Specifications for iOS and `fontScale` on Android

### CODE REVIEW

**Comment by efstathiosntonas** [comment]
@jpudysz amazing, I was manually implementing this for ages. It would be nice to pass our own font family into it, it just adjusts the font size / scaling / weight, right? 

This should be built into react-native 🤔

**Comment by efstathiosntonas** [comment]
@jpudysz thanks, I've already gone through the plugin system and examples, I'm kind of afraid to use them since I'll have to iterate all the keys and I don't know how this could affect performance. I need to measure it. 

Just for reference, this is how I've implemented typography:


<details>
  <summary>Click me</summary>
  
```tsx

export const typography = {
  paragraph: {
    large: {
      regular: {
        fontSize: fontSize(18),
        fontFamily: textRegular,
        fontWeight: "400",
        letterSpacing: 0.09
        // lineHeight: fontSize(19.8)
      },
      medium: {
        fontSize: fontSize(18),
        fontFamily: textMedium,
        fontWeight: "500",
        letterSpacing: 0.09
        // lineHeight: fontSize(19.8)
      },
      semibold: {
        fontSize: fontSize(18),
        fontFamily: textSemiBold,
        fontWeight: "600",
        letterSpacing: 0.09
        // lineHeight: fontSize(19.8)
      },
      bold: {
        fontSize: fontSize(18),
        fontFamily: textBold,
        fontWeight: "700",
        letterSpacing: 0.09
        // lineHeight: fontSize(19.8)
      }
    },
....
heading: {
    h1: {
      medium: {
        fontSize: fontSize(36),
        fontFamily: textDisplayMedium,
        fontWeight: "500",
        letterSpacing: -0.72
        // lineHeight: fontSize(39.6)
      },
      semibold: {
        fontSize: fontSize(36),
        fontFamily: textDisplaySemiBold,
        fontWeight: "600",
        letterSpacing: -0.72
        // lineHeight: fontSize(39.6)
      },
      bold: {
        fontSize: fontSize(36),
        fontFamily: textDisplayBold,
        fontWeight: "700",
        letterSpacing: -0.72
        // lineHeight: fontSize(39.6)
      },
      extrabold: {
        fontSize: fontSize(36),
        fontFamily: textDisplayHeavy,
        fontWeight: "800",
        letterSpacing: -0.72
        // lineHeight: fontSize(39.6)
      }
    },
```

usage: 

```json
title: {
  ...theme.typography.h1.medium
}
```


`fontSize` function: 

```tsx
export default function fontSize(size: number, factor = 1) {
  /*
   * Pass it a number, and it will return a font size that's proportional to the screen size.
   */
  const baseFontSize = 12;
  const scaleFactor = Math.min(dim.width, dim.height) / 390; // Math.min is used in case the screen is in landscape mode
  const scaledFontSize = baseFontSize + (size - baseFontSize) * scaleFactor * factor;
  return PixelRatio.roundToNearestPixel(scaledFontSize);
}
```


</details>

**Comment by jpudysz** [comment]
@efstathiosntonas don't worry about the performance. It should add less than 0.01 ms per stylesheet. 

If you still don't want it, then you can always use your function `fontSize` with the `UnistylesRuntime`.

**Comment by efstathiosntonas** [comment]
@jpudysz if you got some free time, can you provide an example with `fontSize` and `UnistylesRuntime`?

**Comment by jpudysz** [comment]
You can access `contentSizeCategory` from `UnistylesRuntime`

```ts
export default function fontSize(size: number, factor = 1) {
  /*
   * Pass it a number, and it will return a font size that's proportional to the screen size.
   */
  const contentSizeCategory = UnistylesRuntime.contentSizeCategory
  
  // do something with contentSizeCategory
  
  const baseFontSize = 12;
  const scaleFactor = Math.min(dim.width, dim.height) / 390; // Math.min is used in case the screen is in landscape mode
  const scaledFontSize = baseFontSize + (size - baseFontSize) * scaleFactor * factor;
  return PixelRatio.roundToNearestPixel(scaledFontSize);
}
``

**Comment by efstathiosntonas** [comment]
perfect!!! thanks! Can't wait for this land!

**Comment by efstathiosntonas** [comment]
this snippet could be part of the docs I believe, what do you think?

**Comment by jpudysz** [comment]
I mean this function needs adjustment, like mapping string values to scaleFactor? IDK, but when it's ready I can list it under content size category docs

**Comment by efstathiosntonas** [comment]
When next RC is out I'll adjust it and post it here

**Comment by jpudysz** [comment]
I want to release it before Christmas

**Comment by efstathiosntonas** [comment]
@jpudysz you mean next .rc or 2.0.0 stable?

**Comment by jpudysz** [comment]
RC, stable should land in first week of January

**Comment by efstathiosntonas** [comment]
@jpudysz I've patched rc1 and this is what I came up with: 

```tsx
const contentSizeCategoryToFontScaleAndroid: { [key: string]: number } = {
  Small: 0.85,
  Default: 1.0,
  Large: 1.15,
  ExtraLarge: 1.3,
  Huge: 1.3
};

const contentSizeCategoryToFontScaleApple: { [key: string]: number } = {
  unspecified: 1.0,
  xSmall: 0.82,
  Small: 0.88,
  Medium: 0.95,
  Large: 1,
  xLarge: 1.12,
  xxLarge: 1.23,
  xxxLarge: 1.35
};

export default function fontSize(size: number) {
  if (isIOS) {
    const userScale =
      contentSizeCategoryToFontScaleApple[UnistylesRuntime.contentSizeCategory];
    return size * userScale;
  } else {
    const userScale =
      contentSizeCategoryToFontScaleAndroid[UnistylesRuntime.contentSizeCategory];
    return size * userScale;
  }
}
```

the mappings are from ChatGPT, I guess they are accurate. It gave me back `AccessibilityXXXX` values too on iOS and according to the typography docs they do exist as AX1,AX2 etc as shown [here](https://developer.apple.com/design/human-interface-guidelines/typography#iOS-iPadOS-larger-accessibility-type-sizes). 

This is what ChatGPT gave me back for iOS

```tsx
const contentSizeCategoryToFontScaleApple: { [key: string]: number } = {
  UIContentSizeCategoryUnspecified: 1.0,
  UIContentSizeCategoryExtraSmall: 0.82,
  UIContentSizeCategorySmall: 0.88,
  UIContentSizeCategoryMedium: 0.95,
  UIContentSizeCategoryLarge: 1.0,
  UIContentSizeCategoryExtraLarge: 1.12,
  UIContentSizeCategoryExtraExtraLarge: 1.23,
  UIContentSizeCategoryExtraExtraExtraLarge: 1.35,
  // Accessibility sizes
  UIContentSizeCategoryAccessibilityMedium: 1.64,
  UIContentSizeCategoryAccessibilityLarge: 1.96,
  UIContentSizeCategoryAccessibilityExtraLarge: 2.31,
  UIContentSizeCategoryAccessibilityExtraExtraLarge: 2.77,
  UIContentSizeCategoryAccessibilityExtraExtraExtraLarge: 3.32
};
```

**Comment by jpudysz** [comment]
Yes, I'm aware of these `AccessibilityXXXX` values. For now, I will ignore them unless someone reports a need to handle them.

It's only usable when you disable auto font scaling in your `Text` component. Otherwise, it will be handled automatically. The idea was to build layouts based on the scale factor, not to strictly manipulate `fontSize`.

**Pull request merged**
